version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/inventory
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=your-secret-key
      - FERNET_KEY=your-fernet-key
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app

  postgres:
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=inventory
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  postgres_data: